assessment2- jonathon
learn-academy-2019-delta/javascript-foundations-assessment-2-jnarbona91 pull request #1
Opened 2019-08-12 15:46 UTC by jnarbona91

2019-08-12 16:25 UTC, DanteCypress requested changes

2019-08-12 16:25 UTC, DanteCypress commented on js-foundations.js
> +    getData: function() {return this.firstName + " " + this.lastName + " is " + this.height + " and has " + this.eyes + " eyes."}
This is great, to make it even more simple consider using _Template literals (Template strings)_.

2019-08-12 16:25 UTC, DanteCypress commented on js-foundations.js
> +console.log(combineArr(amounts, animals))
Take a look at this again. You're close, but missing one component.

2019-08-15 16:21 UTC, merged

2019-08-15 16:21 UTC, sjproctor approved these changes